[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  SECRETS_SCAN_ENABLED = "false"

# Configure secrets scanning exclusions
[build.processing.secrets_scan]
  omit_paths = [
    "docs/",
    "grant-aggregator-apify-actors/",
    "yarn.lock",
    "package-lock.json",
    "*.pdf",
    "*.json"
  ]
  
  omit_keys = [
    "NODE_ENV",
    "PORT"
  ]