[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

# Configure secrets scanning
[build.processing]
  skip_processing = false

# Disable secrets scanning or configure exclusions
[[build.environment.secrets_scan]]
  enabled = false

# Alternative: Exclude specific paths from secrets scanning
# Use this format to exclude specific files or directories
[build.processing.secrets_scan]
  omit_paths = [
    "docs/",
    "grant-aggregator-apify-actors/",
    "yarn.lock",
    "package-lock.json",
    "*.pdf",
    "*.json"
  ]
  
  # Omit specific environment variable names from scanning
  omit_keys = [
    "NODE_ENV",
    "PORT"
  ]